USE SANDBOX_KOMODO ;
USE ROLE ANALYST ;
USE WAREHOUSE LARGE_WH ;
PUT file://~/komodo_research/projects/Metformin_DPP4_V4/code_list/CLIN-2781_ICD.csv @stage_metdpp4 auto_compress=true;
DROP TABLE IF EXISTS SANDBOX_KOMODO.YWEI.METDPP4_DEF_NDC_V4 ;
CREATE TABLE SANDBOX_KOMODO.YWEI.METDPP4_DEF_NDC_V4 (
  "V1" BOOLEAN,
  "Code" VARCHAR(255),
  "Code Type" VARCHAR(255),
  "Description" VARCHAR(255),
  "Type" VARCHAR(255),
  "Notes" BOOLEAN
)
;
COPY INTO SANDBOX_KOMODO.YWEI.METDPP4_DEF_NDC_V4 FROM @stage_metdpp4/CLIN-2781_ICD.csv.gz;
