---
title: "Analysis for Oxbryta Study"
output: html_notebook
---

https://docs.google.com/spreadsheets/d/1Vs8wMBUndpKMF1jx_PVWZskhREAGYaJUudteNMNvviM/edit#gid=0

```{r config}
workdir <- "~/komodo_research/projects/ash_2022"
library(tidyverse)
library(glue)
library(clipr)
library(tictoc)
library(DBI)
library(googlesheets4)
source("~/komodo_research/library/R/utils.R")
source("~/komodo_research/library/R/sql_helper.R")
source("~/komodo_research/library/R/sql_utils.R")
```

```{r connection}
# create ODBC connection
con_odbc <- DBI::dbConnect(
  odbc::odbc(), "snowflake", 
  role = "ANALYST", 
  warehouse = "LARGE_WH"
)

execute_sql("USE DATABASE SANDBOX_KOMODO;")
execute_sql("USE SCHEMA AYWEI;")
# execute_sql("USE ROLE ANALYST;")
# execute_sql("USE WAREHOUSE XLARGE_WH;")
```

```{r gsconnection}
# google sheet auth
gs4_auth(
  email = gargle::gargle_oauth_email(),
  path = NULL,
  scopes = "https://www.googleapis.com/auth/spreadsheets",
  cache = gargle::gargle_oauth_cache(),
  use_oob = gargle::gargle_oob_default(),
  token = gargle::token_fetch("https://www.googleapis.com/auth/spreadsheets")
)

code_list_ss = "1lwGATVIUxa1RMtcfUmpZRoJLEcDadBboyTmTthN2U20"
```

```{r project_spec}
## Table reference
rx_version = '20220613'
mx_version = '20220605'
code_version = '20220606'
query_start_date = '2019-01-01'
query_end_date = '2022-12-31'
## Output table names
prefix = 'SCD'
```

```{r code_list}
# create a code list for scd, voc
voc_diag_sql = get_code(c('D570%', 'D5721%', 'D5741%', 'D5743%', 'D5745%', 'D5781%'), method = 'pattern', type = 'diag')
scd_diag_sql = get_code(c('D570%', 'D571%', 'D572%', 'D574%', 'D578%'), method = 'pattern', type = 'diag')
print(voc_diag <- read_query(voc_diag_sql))
print(scd_diag <- read_query(scd_diag_sql))
sheet_write(voc_diag, ss = code_list_ss, sheet = 'voc')
sheet_write(scd_diag, ss = code_list_ss, sheet = 'scd')
```

```{r code_list2}
# search all NDCs
oxbryta_ndc_sql = get_code(c('oxbryta'), method = 'name', type = 'ndc')
hydroxyurea_ndc_sql = get_code(c('hydroxyurea'), method = 'name', type = 'ndc')
adakveo_ndc_sql = get_code(c('adakveo'), method = 'name', type = 'ndc')
endari_ndc_sql = get_code(c('endari'), method = 'name', type = 'ndc')

print(oxbryta_ndc <- read_query(oxbryta_ndc_sql))
print(hydroxyurea_ndc <- read_query(hydroxyurea_ndc_sql))
print(adakveo_ndc <- read_query(adakveo_ndc_sql))
print(endari_ndc <- read_query(endari_ndc_sql))

sheet_write(oxbryta_ndc, ss = code_list_ss, sheet = 'oxbryta')
sheet_write(hydroxyurea_ndc, ss = code_list_ss, sheet = 'hydroxyurea')
sheet_write(adakveo_ndc, ss = code_list_ss, sheet = 'adakveo')
sheet_write(endari_ndc, ss = code_list_ss, sheet = 'endari')
```
```{r code_list3}
cci = read_query(glue("SELECT * FROM MAP_VOCABULARY.RXNORM_{code_version}.CHARLSON_CODE;"))
sheet_write(cci, ss = code_list_ss, sheet = 'cci')
transfusion = range_speedread(code_list_ss, sheet = 'transfusion')
colnames(transfusion) <- tolower(colnames(transfusion))
print(cci)
print(transfusion)
```

```{r code_list4}
# create code lists:
# code_list will be queried from the whole DB
# subsample_code_list will be searched within a small list of patients
code_list <- 
  bind_rows(
    voc_diag %>% select(code, code_description) %>% mutate(codetype = "ICD10CM", event = "voc"),
    scd_diag %>% select(code, code_description) %>% mutate(codetype = "ICD10CM", event = "scd"),
    oxbryta_ndc %>% select(ndc, cui_l1_name) 
      %>% rename(code = ndc, code_description = cui_l1_name) 
      %>% mutate(codetype = "NDC", event = "oxbryta"),
    hydroxyurea_ndc %>% select(ndc, cui_l1_name) 
      %>% rename(code = ndc, code_description = cui_l1_name) 
      %>% mutate(codetype = "NDC", event = "hydroxyurea"),
    adakveo_ndc %>% select(ndc, cui_l1_name) 
      %>% rename(code = ndc, code_description = cui_l1_name) 
      %>% mutate(codetype = "NDC", event = "adakveo"),
    endari_ndc %>% select(ndc, cui_l1_name) 
      %>% rename(code = ndc, code_description = cui_l1_name) 
      %>% mutate(codetype = "NDC", event = "endari")
  )

sheet_write(code_list, ss = code_list_ss, sheet = 'code_list')

subsample_code_list <-
  bind_rows(
    transfusion %>% select(code, codetype, code_description) %>% mutate(event = 'transfusion'),
    cci %>% select(icd, charlson_category) %>%
      rename(code = icd, code_description = charlson_category) %>%
      mutate(codetype = 'ICD10CM', event = 'cci') %>%
      select(code, codetype, code_description, event)
  )
sheet_write(subsample_code_list, ss = code_list_ss, sheet = 'subsample_code_list')

write_csv(code_list, file = file.path(workdir, "code_list.csv"))
write_csv(code_list, file = file.path(workdir, "subsample_code_list.csv"))
```

```{r upload_code_list}
bulk_upload(
  conn = con_odbc,
  dir = workdir,
  filename = "code_list.csv", 
  stage_name = "stage_kr",
  table_full_name = "SANDBOX_KOMODO.AYWEI.SCD_CODE_LIST",
  create_stage = FALSE,
  database = 'SANDBOX_KOMODO',
  role = 'ANALYST',
  warehouse = 'LARGE_WH',
  save_sql = TRUE,
  run_sql = TRUE,
  snowsql_profile = 'ywei'
)

bulk_upload(
  conn = con_odbc,
  dir = workdir,
  filename = "subsample_code_list.csv", 
  stage_name = "stage_kr",
  table_full_name = "SANDBOX_KOMODO.AYWEI.SCD_CODE_LIST_SUB",
  create_stage = FALSE,
  database = 'SANDBOX_KOMODO',
  role = 'ANALYST',
  warehouse = 'LARGE_WH',
  save_sql = TRUE,
  run_sql = TRUE,
  snowsql_profile = 'ywei'
)
```
