---
title: "Oxbryta Adherence Study vs More Drugs"
output: html_notebook
---

Code List: Same list as SCD study <https://docs.google.com/spreadsheets/d/1lwGATVIUxa1RMtcfUmpZRoJLEcDadBboyTmTthN2U20/edit#gid=0>

Oxbryta Results: <https://docs.google.com/spreadsheets/d/1RhK4YaLlQ1EHFdyD6QESekOvmVWlnzzftf9aZbb5cPQ/edit#gid=0>

Oxbryta and Others(hydroxyurea, adakveo, endari): <https://docs.google.com/spreadsheets/d/1IVhtmWuXChkAv3Z5xrDoUxkCtqfIj_l6ebAVaRB4BlU/edit#gid=0>

```{r config}
repo_dir <- "~/komodo/code/komodo_research"
proj_dir <- file.path(repo_dir, 'projects', 'ash_2022')
lib_dir <- file.path(repo_dir, 'library')
code_dir <- file.path(proj_dir, 'code')
model_dir <- file.path(proj_dir, 'model')
plot_dir <- file.path(proj_dir, 'plot')
dir.create(code_dir, showWarnings = F)
dir.create(model_dir, showWarnings = F)
dir.create(plot_dir, showWarnings = F)

library(tidyverse)
library(glue)
library(clipr)
library(tictoc)
library(DBI)
library(googlesheets4)
library(googledrive)
library(MatchIt)
library(table1)
library(cobalt)
library(boot)
library(parallel)
library(betareg)

source(file.path(lib_dir, "R/utils.R"))
source(file.path(lib_dir, "R/sql_helper.R"))
source(file.path(lib_dir, "R/sql_utils.R"))
```

```{r connection}
# create ODBC connection
con_odbc <- DBI::dbConnect(
  odbc::odbc(), "snowflake", 
  role = "ANALYST", 
  warehouse = "LARGE_WH"
)

execute_sql("USE DATABASE SANDBOX_KOMODO;")
execute_sql("USE SCHEMA AYWEI;")
execute_sql("USE ROLE ANALYST;")
execute_sql("USE WAREHOUSE XLARGE_WH;")
```

```{r gsconnection}
# google sheet auth
gs4_auth(
  email = gargle::gargle_oauth_email(),
  path = NULL,
  scopes = "https://www.googleapis.com/auth/spreadsheets",
  cache = gargle::gargle_oauth_cache(),
  use_oob = gargle::gargle_oob_default(),
  #token = gs4_token()
  token = gargle::token_fetch("https://www.googleapis.com/auth/spreadsheets")
)
code_list_ss = "1lwGATVIUxa1RMtcfUmpZRoJLEcDadBboyTmTthN2U20"
output_ss = "1RhK4YaLlQ1EHFdyD6QESekOvmVWlnzzftf9aZbb5cPQ"
output2_ss = "1IVhtmWuXChkAv3Z5xrDoUxkCtqfIj_l6ebAVaRB4BlU"

proj_drive_url = "https://drive.google.com/drive/folders/1Dfs8-sJUgx-5rfbLJIY2igNIpPJ4rsX-"
proj_drive = drive_get(path = proj_drive_url)
#drive_mkdir('plot', path = proj_drive, overwrite = FALSE)
plot_drive = drive_ls(proj_drive, 'plot')
```

```{r project_spec}
## Table reference
rx_version = '20220613'
mx_version = '20220605'
code_version = '20220606'
query_start_date = '2016-01-01'
query_end_date = '2022-12-31'
## Output table names
prefix = 'Oxbryta2'
cci_def = glue("MAP_VOCABULARY.RXNORM_{code_version}.CHARLSON_CODE")
cci_score = glue("MAP_VOCABULARY.RXNORM_{code_version}.CHARLSON_SCORE")
```

## Code definition

Use the same code list as the SCD study.

## Create Study Eligible Cohort

Use same files for SCD study.

```{r get_query}
code_list_table = glue('scd_code_list')
code_list_sub_table = glue('scd_code_list_sub')
tic("Mx Encounter")
# EY: for readibility, preferred if this is written as:
# sql_mx = glue("
#     create or replace table scd_mx_encounter as",
#     query_event_mx(
#       code_list_table = code_list_table,
#       mx_version = mx_version,
#       start_date = query_start_date, end_date = query_end_date
#       ),
#     ";"
#     )

sql_mx = glue("
    create or replace table scd_mx_encounter as
    {query_event_mx(
      code_list_table = code_list_table,
      mx_version = mx_version,
      start_date = query_start_date, end_date = query_end_date
      )
    }
    ;
")
execute_sql(sql_mx)
toc()

tic("Rx Encounter")
sql_rx = glue("
    create or replace table scd_rx_encounter as
    {query_event_rx(
      code_list_table = code_list_table,
      rx_version = rx_version,
      start_date = query_start_date, end_date = query_end_date
      )
    }
    ;
")
execute_sql(sql_rx)
toc()
```

```{r build_cohort}
# EY: this gets patients whose first claim falls after 2017-01-01.
cohort_start_date = '2017-01-01'
sql = glue("  
    create or replace table {prefix}_cohort as
    with query as (
      select upk_key2, claim_date, code, codetype, event as cohort
      from scd_rx_encounter where event in ('oxbryta','hydroxyurea', 'adakveo', 'endari')
      union
      select upk_key2, claim_date, code, codetype, event as cohort
      from scd_mx_encounter where event in ('oxbryta','hydroxyurea', 'adakveo', 'endari')
    ),
    first_claim as(
    select upk_key2, claim_date as index_date, code, codetype, cohort
    from query
    qualify row_number() over(partition by upk_key2, cohort order by claim_date) = 1
    )
    select * from first_claim where index_date >= '{cohort_start_date}'
    ;
")
execute_sql(sql)
```

```{r add_flag}
demo_table = glue("CDO_PROD.CDO_PATIENT.PATIENT_DEMOGRAPHICS_UPK2_SUMMARY")
execute_sql("USE ROLE CDO_PROD_RESTRICTED;")
sql = glue("
  create or replace table {prefix}_demo as
  select * from {demo_table}
  where upk_key2 in (select upk_key2 from {prefix}_cohort)
;")
execute_sql(sql)
execute_sql(glue("grant ownership on table {prefix}_demo to role analyst; "))
execute_sql("USE ROLE ANALYST;")

bene_table = glue("MAP_ENCOUNTERS.MX_ENCOUNTERS_{mx_version}.BENEFICIARY_LS_GA")
sql = glue("
  create or replace table {prefix}_cohort_w_flags as
  with elig as (
    select c.upk_key2, c.cohort,
      count_if(c.index_date - 365 between e.start_date and e.end_date and c.index_date between e.start_date and e.end_date) as elig_b_1y,
      count_if(c.index_date - 183 between e.start_date and e.end_date and c.index_date between e.start_date and e.end_date) as elig_b_6m,
      count_if(c.index_date + 1 between e.start_date and e.end_date and c.index_date + 365 between e.start_date and e.end_date) as elig_f_1y,
      count_if(c.index_date + 1 between e.start_date and e.end_date and c.index_date + 183 between e.start_date and e.end_date) as elig_f_6m
    from {prefix}_cohort c
    inner join ce_{mx_version} e
    on c.upk_key2 = e.upk_key2 
    group by c.upk_key2, c.cohort
  ),
  scd as (
    select c.upk_key2, c.cohort, count(*) as n_scd_before
    from {prefix}_cohort c
    inner join scd_mx_encounter m
    on c.upk_key2 = m.upk_key2 
      and m.event = 'scd'
      and m.claim_date between c.index_date - 365 and c.index_date
    group by c.upk_key2, c.cohort
  ),
  bene as (
    select distinct c.upk_key2, c.cohort,
      first_value(patient_dob) over (partition by c.upk_key2 order by patient_dob nulls last) as patient_dob,
      first_value(patient_gender) over (partition by c.upk_key2 order by patient_gender nulls last) as patient_gender,
      first_value(patient_state) over (partition by c.upk_key2 order by patient_state nulls last) as patient_state,
      first_value(patient_zip) over (partition by c.upk_key2 order by patient_zip nulls last) as patient_zip
    from {prefix}_cohort c
    left join {bene_table} b
    on c.upk_key2 = b.upk_key2 and c.index_date between b.closed_start_date and b.closed_end_date
  ),
  demo as (
    select c.upk_key2, c.cohort, PATIENT_RACE_OMB, PATIENT_ETHNICITY_OMB
    from {prefix}_cohort c
    left join {prefix}_demo d
    on c.upk_key2 = d.upk_key2
  )
  select distinct c.upk_key2, index_date, c.cohort,
    coalesce(elig_b_1y, 0) as elig_b_1y, 
    coalesce(elig_b_6m, 0) as elig_b_6m, 
    coalesce(elig_f_1y, 0) as elig_f_1y, 
    coalesce(elig_f_6m, 0) as elig_f_6m, 
    coalesce(n_scd_before, 0) as n_scd_before,
    patient_dob, patient_gender, patient_state, patient_zip,
    PATIENT_RACE_OMB, PATIENT_ETHNICITY_OMB,
    year(index_date) - year(patient_dob) as age
    --coalesce(n_adakveo, 0) as n_adakveo, 
    --coalesce(n_endari, 0) as n_endari
  from {prefix}_cohort c
  left join elig e
  on c.upk_key2 = e.upk_key2 and c.cohort = e.cohort
  left join scd m
  on c.upk_key2 = m.upk_key2 and c.cohort = m.cohort
  left join bene b
  on c.upk_key2 = b.upk_key2 and c.cohort = b.cohort
  left join demo d
  on c.upk_key2 = d.upk_key2 and c.cohort = d.cohort
  ;
")
execute_sql(sql)
```

```{r cohort_funnel}
# EY: possibly want to write this logic as a loop
cohort_funnel <- function() {
  select_str = "cohort, count(distinct upk_key2) as n_bene"
  sql = glue("
      select 'a. all users in study window' as criteria, {select_str}
      from {prefix}_cohort_w_flags
      group by cohort
      
      union all
      select 'b1. continuous enrollment (1y before)' as criteria, {select_str}
      from {prefix}_cohort_w_flags
      where elig_b_1y > 0
      group by cohort
      
      union all
      select 'b2. continuous enrollment (6m after)' as criteria, {select_str}
      from {prefix}_cohort_w_flags
      where elig_b_1y > 0 and elig_f_6m > 0
      group by cohort
      
      union all
      select 'b3. continuous enrollment (1y after)' as criteria, {select_str}
      from {prefix}_cohort_w_flags
      where elig_b_1y > 0 and elig_f_1y > 0
      group by cohort
      
      union all
      select 'c. w/ sickle-cell disease diagnosis' as criteria, {select_str}
      from {prefix}_cohort_w_flags
      where elig_b_1y > 0 and elig_f_1y > 0 and n_scd_before > 0
      group by cohort
  
      -- union all
      -- select 'd. age >= 12 on index date' as criteria, {select_str}
      -- from {prefix}_cohort_w_flags
      -- where elig_b_1y > 0 and elig_f_1y > 0 and n_scd_before > 0 and age >= 12
      -- group by cohort
      
      union all
      select 'd. index date after 2019/12' as criteria, {select_str}
      from {prefix}_cohort_w_flags
      where elig_b_1y > 0 and elig_f_1y > 0 and n_scd_before > 0 and index_date >= '2019-12-01'
      group by cohort
      
      order by cohort, criteria
    ;
  ")
}

print(cohort_funnel <- read_query(cohort_funnel()))
```

```{r final_cohort}
sql = glue("
  create or replace table {prefix}_final_cohort as
  select *
  from {prefix}_cohort_w_flags
  where elig_b_1y > 0 and elig_f_1y > 0 and n_scd_before > 0
  -- and age >= 12
  ;
")
execute_sql(sql)
```

```{r get_adherence}
rx_table1 <- glue("(select *, event as cohort from scd_rx_encounter where event = 'oxbryta')")
cohort_table1 <- glue("(select * from {prefix}_final_cohort where cohort = 'oxbryta')")
rx_table2 <- glue("(select *, event as cohort from scd_rx_encounter where event = 'hydroxyurea')")
cohort_table2 <- glue("(select * from {prefix}_final_cohort where cohort = 'hydroxyurea')")
rx_table4 <- glue("(select *, event as cohort from scd_rx_encounter where event = 'endari')")
cohort_table4 <- glue("(select * from {prefix}_final_cohort where cohort = 'endari')")

sql <- glue("
  create or replace table {prefix}_adakveo_rx as
  with claims as(
    select upk_key2, claim_date, 
      case when days_supply <= 3 then null else days_supply end as days_supply, 
      code, codetype, event as cohort 
    from scd_rx_encounter where event = 'adakveo'
    union all
    select upk_key2, claim_date, 
      null as days_supply, code, 
      codetype, event as cohort 
    from scd_mx_encounter where event = 'adakveo'
    order by upk_key2, claim_date
  ),
  dedup as (
    select upk_key2, claim_date, cohort, max(days_supply) as days_supply
    from claims
    group by upk_key2, claim_date, cohort
  ),
  add_row as (
    select *, row_number() over(partition by upk_key2, cohort order by claim_date) as n
    from dedup
  )
  select upk_key2, cohort, claim_date,
    case 
      when days_supply is null and n <= 2 then 14
      when days_supply is null and n > 2 then 28
      else days_supply
    end as days_supply
  from add_row
  ;
  ")
execute_sql(sql)

rx_table3 <- glue("(select * from {prefix}_adakveo_rx)")
cohort_table3 <- glue("(select * from {prefix}_final_cohort where cohort = 'adakveo')")

# EY: more usage of glue() with named arguments would help with readability.

# EY: this seems overly complicated how you switch between R functions and SQL code. 
# Writing it this way is a way to minimize the switching back and forth:

# sql <- glue("create or replace table {prefix}_adherence as ",
#             glue(read_sql("get_adherence"), rx_table=rx_table1,
#                  cohort_table=cohort_table1, days_at_risk=365),
#             "union all",
#             glue(read_sql("get_adherence"), rx_table=rx_table1,
#                  cohort_table=cohort_table2, days_at_risk=365),
#             "union all",
#             ...)

# Or preferably written as a for loop that does the above.


sql <- glue("
  create or replace table {prefix}_adherence as
  ({get_adherence(rx_table1, cohort_table1, days_at_risk = 365)})
  union all
  ({get_adherence(rx_table2, cohort_table2, days_at_risk = 365)})
  union all
  ({get_adherence(rx_table3, cohort_table3, days_at_risk = 365)})
  union all
  ({get_adherence(rx_table4, cohort_table4, days_at_risk = 365)})
  ;")
execute_sql(sql)
```

```{r step_7_more_encounters}
# create encounter table for covariates and outcome

# EY: glue wrapping these strings is unnecessary
code_list_table = 'scd_code_list'
code_list_sub_table = 'scd_code_list_sub'
patient_table = "(select upk_key2 from scd_mx_encounter union select upk_key2 from scd_rx_encounter)"
tic("Mx Encounter")

# EY: preferred formatting:
sql_mx = glue("
    create or replace table scd_mx_encounter_sub as ",
    query_event_mx(
      code_list_table = code_list_sub_table,
      patient_table = patient_table,
      mx_version = mx_version,
      start_date = query_start_date, end_date = query_end_date
      ),
    ";")

execute_sql(sql_mx)
toc()
```

```{r clean_voc_inpatient_stays}
# EY: this allowable gap logic for determining duration of inpatient visits seems very useful, it's probably worthwhile to pull out as its own function for the future.
ip_allowable_gap = 2
# 0 means allow consecutive stays not merge, so 9/1-9/15 and 9/16-9/30
# 1 means gap should be at least one full day, so 9/1-9/15 and 9/17-9/30
sql = glue("
    create or replace table scd_voc_ip_stay as
    with voc_data as(
      select distinct
        upk_key2, visit_start_date, visit_end_date
      from scd_mx_encounter
      where event = 'voc' and visit_setting_of_care = 'Inpatient Visit'
    ),
    gap as (
        -- construct a gap dataset. The arbitrary early date does not matter.
        select upk_key2, '1970-01-01' as gap_start_date, min(visit_start_date -1) as gap_end_date
        from voc_data
        group by upk_key2
        union all
        select upk_key2,
            max(visit_end_date + 1) over (partition by upk_key2 order by visit_start_date) as gap_start_date,
            lead(visit_start_date - 1) over (partition by upk_key2 order by visit_start_date) as gap_end_date
        from voc_data qualify gap_end_date - gap_start_date + 1 >= {ip_allowable_gap}
        union all
        select upk_key2, max(visit_end_date + 1) as gap_start_date, null as gap_end_date
        from voc_data
        group by upk_key2
    )
    select
        upk_key2,
        gap_end_date + 1 as visit_start_date,
        lead(gap_start_date -1) over (partition by upk_key2 order by gap_start_date) as visit_end_date,
        'Inpatient Visit' as visit_setting_of_care
    from gap qualify gap_end_date IS NOT null
    ;
")
execute_sql(sql)

```

```{r get_covariates}
# EY: this is hard to follow for how long the query is. Recommended to break this up into multiple queries for each covariate using create temp table statements, then merging them together in the end.
# EY: you can consider moving the repeated logic in the below query into Snowflake user-defined functions

sql = glue("
    create or replace table {prefix}_final_cohort_w_cov as
    with 
    voc_data as(
      select distinct
        upk_key2, visit_setting_of_care, 
          coalesce(visit_start_date, claim_date) as visit_start_date,
          coalesce(visit_end_date, claim_date) as visit_end_date
      from scd_mx_encounter
      where event = 'voc' and visit_setting_of_care != 'Inpatient Visit'
      union
      select upk_key2, visit_setting_of_care, visit_start_date, visit_end_date
      from scd_voc_ip_stay
    ),
    voc as (
      select a.upk_key2, a.cohort,
        count(distinct case when 
          b.visit_start_date between a.index_date - 365 and a.index_date 
          then visit_start_date else null end
        ) as n_pre_voc,
        count(distinct case when 
          b.visit_start_date between a.index_date - 365 and a.index_date 
          and visit_setting_of_care = 'Inpatient Visit'
          then visit_start_date else null end
        ) as n_pre_voc_ip,
        count(distinct case when 
          b.visit_start_date between a.index_date - 365 and a.index_date 
          and visit_setting_of_care = 'Emergency Room Visit'
          then visit_start_date else null end
        ) as n_pre_voc_er,
        count(distinct case when 
          b.visit_start_date between a.index_date - 365 and a.index_date 
          and visit_setting_of_care in ('Inpatient Visit', 'Emergency Room Visit')
          then visit_start_date else null end
        ) as n_pre_voc_iper,
        
        count(distinct case when 
          b.visit_start_date between a.index_date + 1 and a.index_date + 365 
          then visit_start_date else null end
        ) as n_post_voc,
        count(distinct case when 
          b.visit_start_date between a.index_date + 1 and a.index_date + 365 
          and visit_setting_of_care = 'Inpatient Visit'
          then visit_start_date else null end
        ) as n_post_voc_ip,
        count(distinct case when 
          b.visit_start_date between a.index_date + 1 and a.index_date + 365 
          and visit_setting_of_care = 'Emergency Room Visit'
          then visit_start_date else null end
        ) as n_post_voc_er,
        count(distinct case when 
          b.visit_start_date between a.index_date + 1 and a.index_date + 365
          and visit_setting_of_care in ('Inpatient Visit', 'Emergency Room Visit')
          then visit_start_date else null end
        ) as n_post_voc_iper
      from {prefix}_final_cohort a
      inner join voc_data b
      on a.upk_key2 = b.upk_key2 and b.visit_start_date between a.index_date - 365 and a.index_date + 365
      group by a.upk_key2, a.cohort
    ),
    
    transfusion as (
      select a.upk_key2, a.cohort,
        count(distinct claim_date) as n_transfusion
      from {prefix}_final_cohort a
      inner join scd_mx_encounter_sub b
      on a.upk_key2 = b.upk_key2 and b.claim_date between a.index_date - 365 and a.index_date
      where event = 'transfusion'
      group by a.upk_key2, a.cohort
    ),
    
    drugs as (
      select a.upk_key2, a.cohort,
        count_if(event = 'hydroxyurea') as n_hydroxyurea,
        count_if(event = 'adakveo') as n_adakveo,
        count_if(event = 'endari') as n_endari,
        count_if(b.claim_date between a.index_date - 365 and a.index_date) as n_voc_treatment_pre,
        count_if(b.claim_date between a.index_date and a.index_date + 365) as n_voc_treatment_post
      from {prefix}_final_cohort a
      inner join scd_rx_encounter b
      on a.upk_key2 = b.upk_key2
      where event in ('hydroxyurea', 'adakveo', 'endari')
      group by a.upk_key2, a.cohort
    ),
    cci_data as(
      select distinct a.upk_key2, a.cohort, c.charlson_category
      from {prefix}_final_cohort a
      inner join scd_mx_encounter_sub b
      on a.upk_key2 = b.upk_key2 and b.claim_date between a.index_date - 365 and a.index_date
      inner join {cci_def} c
      on b.code = c.icd
      where event = 'cci'
      union
      select upk_key2, cohort, case 
          when age < 50 then '< 50'
          when age < 60 then '50-59'
          when age < 70 then '60-69'
          when age < 80 then '70-79'
          when age >= 80 then '80+'
          else '< 50'
      end as charlson_category
      from {prefix}_final_cohort
    ),
    cci as(
      select upk_key2, cohort, sum(charlson_score) as charlson_score
      from cci_data a
      inner join {cci_score} d
      on a.charlson_category = d.charlson_category
      group by upk_key2, cohort
    )
    select c.*,
      coalesce(n_transfusion, 0) as n_transfusion,
      coalesce(charlson_score, 0) as charlson_score,
      
      coalesce(n_pre_voc, 0) as n_pre_voc,
      coalesce(n_pre_voc_ip, 0) as n_pre_voc_ip,
      coalesce(n_pre_voc_er, 0) as n_pre_voc_er,
      coalesce(n_pre_voc_iper, 0) as n_pre_voc_iper,
      
      coalesce(n_post_voc, 0) as n_post_voc,
      coalesce(n_post_voc_ip, 0) as n_post_voc_ip,
      coalesce(n_post_voc_er, 0) as n_post_voc_er,
      coalesce(n_post_voc_iper, 0) as n_post_voc_iper,      
      
      case
        when age < 12 then '0. 0-11'
        when age < 20 then '1. 12-19'
        when age < 30 then '2. 20-29'
        when age < 50 then '3. 30-49'
        when age >= 50 then '9. 50+'
        else 'Missing'
      end as age_cat,
      case
        when patient_gender = 'F' then 'Female'
        when patient_gender = 'M' then 'Male'
        else 'Missing'
      end as gender,
      case
        when patient_state in ('CT', 'ME', 'MA', 'NH', 'RI', 
                             'VT', 'NJ', 'NY', 'PA') then '1. Northeast'
        when patient_state in ('IL', 'IN', 'MI', 'OH', 'WI', 
                             'IA', 'KS', 'MO', 'MN', 'NE', 'ND',
                             'SD') then '2. Midwest'
        when patient_state in ('DE', 'FL', 'GA', 'MD', 'NC', 
                             'SC', 'VA', 'DC', 'WV', 'AL',
                             'KY', 'MS', 'TN', 'AR', 'LA',
                             'OK', 'TX') then '3. South'
        when patient_state in ('AZ', 'CO', 'ID', 'MT', 'NV', 
                             'NM', 'UT', 'WY', 'AK', 'CA',
                             'HI', 'OR', 'WA') then '4. West'
        when patient_state in ('PR', 'VI') then '5. US Territories'
        else 'Missing'
      end as region,
      year(c.index_date) as year,
      quarter(c.index_date) as quarter,
      case
        when coalesce(charlson_score, 0) < 5 then to_char(coalesce(charlson_score, 0))
        when coalesce(charlson_score, 0) >=5 then '5+'
      end as cci,
      case
        when coalesce(n_transfusion, 0) < 5 then to_char(coalesce(n_transfusion, 0))
        else '5+'
      end as transfusion,
      coalesce(n_voc_treatment_pre, 0) > 0 as voc_treatment_pre,
      coalesce(n_voc_treatment_post, 0) > 0 as voc_treatment_post,
      case
        when coalesce(n_pre_voc, 0) < 5 then to_char(coalesce(n_pre_voc, 0))
        else '5+'
      end as pre_voc,
      case
        when coalesce(n_pre_voc_ip, 0) < 5 then to_char(coalesce(n_pre_voc_ip, 0))
        else '5+'
      end as pre_voc_ip,
      case
        when coalesce(n_pre_voc_er, 0) < 5 then to_char(coalesce(n_pre_voc_er, 0))
        else '5+'
      end as pre_voc_er,
      case
        when coalesce(n_pre_voc_iper, 0) < 5 then to_char(coalesce(n_pre_voc_iper, 0))
        else '5+'
      end as pre_voc_iper,
      case
        when coalesce(n_post_voc, 0) < 5 then to_char(coalesce(n_post_voc, 0))
        else '5+'
      end as post_voc,
      case
        when coalesce(n_post_voc_ip, 0) < 5 then to_char(coalesce(n_post_voc_ip, 0))
        else '5+'
      end as post_voc_ip,
      case
        when coalesce(n_post_voc_er, 0) < 5 then to_char(coalesce(n_post_voc_er, 0))
        else '5+'
      end as post_voc_er,
      case
        when coalesce(n_post_voc_iper, 0) < 5 then to_char(coalesce(n_post_voc_iper, 0))
        else '5+'
      end as post_voc_iper,
      n_claims,
      pdc_at_risk
    from {prefix}_final_cohort c
    left join voc v
    on c.upk_key2 = v.upk_key2 and c.cohort = v.cohort
    left join transfusion t
    on c.upk_key2 = t.upk_key2 and c.cohort = t.cohort
    left join drugs d
    on c.upk_key2 = d.upk_key2 and c.cohort = d.cohort
    left join cci i
    on c.upk_key2 = i.upk_key2 and c.cohort = i.cohort
    left join {prefix}_adherence a
    on c.upk_key2 = a.upk_key2 and c.cohort = a.cohort
    ;
")
execute_sql(sql)
```

```{r download_to_local}
cohort <- 
  tbl(con_odbc, Id(database = "SANDBOX_KOMODO", schema = "AYWEI", table = "OXBRYTA2_FINAL_COHORT_W_COV")
) %>% collect()
colnames(cohort) <- tolower(colnames(cohort))
cohort <- cohort %>% 
  mutate(
    year_quarter = factor(paste0(year, quarters(index_date))), 
    age_cat = factor(age_cat),
    cohort = factor(cohort, levels = c("oxbryta", "hydroxyurea", "adakveo", "endari")),
    region = factor(region))
cohort <- cohort %>%
  mutate(pdc_augmented = pmin(pdc_at_risk, 1-1e-3),
         w_transfusion = n_transfusion > 0,
         pre_voc_ip3 = case_when(
           n_pre_voc_ip == 0 ~ '0',
           n_pre_voc_ip == 1 ~ '1',
           n_pre_voc_ip == 2 ~ '2',
           TRUE ~ '3+'
         ),
         pre_voc_er3 = case_when(
           n_pre_voc_er == 0 ~ '0',
           n_pre_voc_er == 1 ~ '1',
           n_pre_voc_er == 2 ~ '2',
           TRUE ~ '3+'
         ),
         cci_score = case_when(
           charlson_score == 0 ~ '0',
           charlson_score <= 3 ~ '1-3',
           TRUE ~ '4+'
         )
      )
region_labs <- levels(cohort$region)[1:4]

cohort2 <-
  cohort %>% filter(index_date >= '2019-12-01', 
                    index_date <= '2021-06-30', 
                    !is.na(gender), !is.na(age)) %>%
  mutate(region = factor(ifelse(region == 'Missing', 3, region), labels = region_labs),
         year_quarter = factor(year_quarter),
         age_cat = factor(age_cat))

# sheet_write(cohort, ss = output2_ss, sheet = 'patient_cohort')
```

```{r upload_cohort_funnal}
cohort_funnel_reshape <-
  cohort_funnel %>% 
  arrange(criteria, cohort) %>% 
  pivot_wider(id_cols = "criteria", names_from = c("cohort"), values_from = c("n_bene"))
print(cohort_funnel_reshape)
sheet_write(cohort_funnel_reshape, ss = output2_ss, sheet = 'cohort_funnel')
```

```{r cohort_summary}
covariates <- get_covariates(
  cohort, 
  covariates = 
    c('age_cat', 'gender', 'region', 'patient_state', 'year_quarter', 'cci_score', 'w_transfusion', 'patient_race_omb', 'patient_ethnicity_omb',
      'pre_voc', 'pre_voc_ip', 'pre_voc_er', 'pre_voc_iper', 
      'post_voc', 'post_voc_ip', 'post_voc_er', 'post_voc_iper',
      'n_claims', 'pdc_at_risk'))
print(covariates$tbl_bal)
sheet_write(covariates$tbl_bal, ss = output2_ss, sheet = 'covariates')
```

```{r cohort_summary2}
covariates2 <- get_covariates(
  cohort2, 
  covariates = 
    c('age_cat', 'gender', 'region', 'year_quarter', 'cci_score', 'w_transfusion', 'patient_race_omb', 'patient_ethnicity_omb',
      'pre_voc_ip3', 'pre_voc_er3', 
      'n_claims', 'pdc_at_risk'))
print(covariates2$tbl_bal)
sheet_write(covariates2$tbl_bal, ss = output2_ss, sheet = 'covariates2')
```

```{r adherence_summary_univariate}
summary_cts_uni <- function(df, summ_var, group_var_list = NULL) {
  summ <- function(summ_df, summ_var) {
    summ_df %>% dplyr::summarize(
      n = n(), 
      mean = mean(.data[[summ_var]]), 
      sd = sd(.data[[summ_var]]),
      min = min(.data[[summ_var]]), 
      p1 = quantile(.data[[summ_var]], 0.01),
      p5 = quantile(.data[[summ_var]], 0.05),
      p25 = quantile(.data[[summ_var]], 0.25),
      p50 = quantile(.data[[summ_var]], 0.50),
      p75 = quantile(.data[[summ_var]], 0.75),
      p95 = quantile(.data[[summ_var]], 0.95),
      p99 = quantile(.data[[summ_var]], 0.99),
      max = max(.data[[summ_var]])
      )
  }
  summ_total <- summ(df, summ_var)
  if (is.null(group_var_list)) {
    return(summ_total)
  } else {
    res_list <- lapply(group_var_list, function(group_var) {
      summ_df <- df %>% group_by(.data[[group_var]])
      summ_by_group <- summ(summ_df, summ_var)
      res <- data.frame(var = group_var, summ_by_group)
      names(res)[2] <- "level"
      res
    })
    res_by_group <- do.call(rbind, res_list)
    res_total <- data.frame(var = "total", level = "", summ_total)
    
    summ_combine <- rbind(res_total, res_by_group)
    return(summ_combine)
  }
}
for (drug in c("oxbryta", "hydroxyurea", "adakveo", "endari")) {
  print(summ_by_group <- 
          summary_cts_uni(cohort2 %>% filter(cohort == drug), 
                          'pdc_at_risk', 
                        c('age_cat', 'region', 'year_quarter', 'cci_score', 'w_transfusion', 'pre_voc_ip3', 'pre_voc_er3', 'patient_race_omb')))
  
  sheet_write(summ_by_group, ss = output2_ss, sheet = paste0('adherence_', drug))
}
```

```{r adherence_summary_multivariate}
run_model <- function(data, method = c('beta', 'lm')) {
  if (method == 'beta') {
    reg_fun = betareg
  } else if (method == 'lm') {
    reg_fun = lm
  }
  model <- reg_fun(pdc_augmented ~ age_cat + gender + region + cci_score + w_transfusion + pre_voc_ip3 + pre_voc_er3, data = data)
  # print(summary(model))
  # print(stats::AIC(model))
  # print(stats::BIC(model))
  
  if (method == 'beta') {
    coef_df <- data.frame(coef(summary(model))$mean)
    conf_df <- confint(model)
    conf_df <- conf_df[1:(nrow(conf_df)-1),]
  } else if (method == 'lm') {
    coef_df <- data.frame(coef(summary(model)))
    conf_df <- confint(model)
  }  
  res_df <- data.frame(var = rownames(coef_df), coef_df, conf_df)
  res_df
}

settings = c("all", "oxbryta", "hydroxyurea", "adakveo", "endari")
model_list <- lapply(settings, function(s) {
  data = cohort2
  if (s != "all") {
    data = data %>% filter(cohort == s)
  }
  if (s == 'adakveo') {
    data = data %>% filter(age >= 12)
  }
    
  coef_df_lm = run_model(data, "lm")
  sheet_write(coef_df_lm, ss = output2_ss, sheet = paste0('model_', s, '_', 'lm'))
  coef_df_beta = run_model(data, "beta")
  sheet_write(coef_df_beta, ss = output2_ss, sheet = paste0('model_', s, '_', 'beta'))
  return(list(beta = coef_df_beta, lm = coef_df_lm))
})
saveRDS(model_list, file = file.path(model_dir, "final_models.rds"))
```

```{r abstract_table1}
table1 <- get_covariates(
  cohort2, 
  covariates = 
    c('age_cat', 'gender', 'region', 'cci_score', 'w_transfusion', 'pre_voc_ip3', 'pre_voc_er3', 'n_claims', 'pdc_at_risk'))

generic_names <- c('voxelotor', 'hydroxyurea', 'crizanlizumab-tmca', 'L-glutamine')
colnames(table1$tbl_bal) <- paste0(c("", generic_names, "Total", "SMD"), "\n", table1$tbl_bal[1,])
table1$tbl_bal[,1] <- 
  c('N=', 'Age', '  0-11', '  12-19', '  20-29', '  30-49', '  50+',
    'Gender', '  Female', '  Male',
    'Region', '  Northeast', '  Midwest', '  South', '  West',
    'CCI', '  0', '  1-3', '  4+',
    'Transfusion', '  Yes', '  No',
    'VOC (Inpatient)', '  0', '  1', '  2', '  3+',
    'VOC (Emergency Room)', '  0', '  1', '  2', '  3+',
    'Number of Prescriptions', '  Mean (SD)', '  Median [Min, Max]',
    'PDC', '  Mean (SD)', '  Median [Min, Max]'
    )
table1$tbl_bal <-
  table1$tbl_bal %>%
  as_tibble() %>%
  filter(!row_number() %in% c(1, 35, 38)) %>%
  select(-7)

sheet_write(table1$tbl_bal, ss = output2_ss, sheet = 'abstract_table1')
write_csv(table1$tbl_bal, file = file.path(model_dir, 'table1.csv'))
```

```{r abstract_table2}
final_model_tbl <- model_list[[1]]$lm
final_model_tbl$est <- paste0(
  formatC(final_model_tbl[,2], format = 'f', digits = 3),
  ' (',
  formatC(final_model_tbl[,6], format = 'f', digits = 3), 
  ', ', 
  formatC(final_model_tbl[,7], format = 'f', digits = 3),
  ')')
final_model_tbl <- final_model_tbl[, c(1, 8, 5)]
final_model_tbl[,3] <- 
  ifelse(final_model_tbl[,3] < 0.001, '<0.001', formatC(final_model_tbl[,3], format = 'f', digits = 3))
colnames(final_model_tbl) <- c('Covariate', 'Estimate (95% CI)', 'p-Value')

final_model_tbl <- final_model_tbl %>%
  add_row(Covariate = c('age', 'age2'), `Estimate (95% CI)` = c(NA, '(Reference)'), .before = 2) %>%
  add_row(Covariate = c('gender', 'gender2'), `Estimate (95% CI)` = c(NA, '(Reference)'), .before = 8) %>%
  add_row(Covariate = c('region', 'region2'), `Estimate (95% CI)` = c(NA, '(Reference)'), .before = 11) %>%
  add_row(Covariate = c('cci', 'cci2'), `Estimate (95% CI)` = c(NA, '(Reference)'), .before = 16) %>%
  add_row(Covariate = c('trans', 'trans2'), `Estimate (95% CI)` = c(NA, '(Reference)'), .before = 20) %>%
  add_row(Covariate = c('ip', 'ip2'), `Estimate (95% CI)` = c(NA, '(Reference)'), .before = 23) %>%
  add_row(Covariate = c('er', 'er2'), `Estimate (95% CI)` = c(NA, '(Reference)'), .before = 28)

final_model_tbl$Covariate <- 
  c("Intercept",
    "Age", "  0-11", "  12-19", "  20-29", "  30-49", "  50+",
    "Gender", "  Female", "  Male",
    "Region", "  Northeast", "  Midwest", "  South", "  West",
    "CCI", "  0", "  1-3", "  4+",
    "Transfusion", "  No", "  Yes",
    "VOC (Inpatient)", "  0", "  1", "  2", "  3+",
    "VOC (Emergency Room)", "  0", "  1", "  2", "  3+"
    )

rownames(final_model_tbl) <- NULL

sheet_write(final_model_tbl, ss = output2_ss, sheet = 'abstract_table2')
write_csv(final_model_tbl, file = file.path(model_dir, 'table2.csv'))
```
