---
title: "SCD - Oxbryta Study"
output: html_notebook
---

Code List:
https://docs.google.com/spreadsheets/d/1lwGATVIUxa1RMtcfUmpZRoJLEcDadBboyTmTthN2U20/edit#gid=0

Results:
https://docs.google.com/spreadsheets/d/1Vs8wMBUndpKMF1jx_PVWZskhREAGYaJUudteNMNvviM/edit#gid=0

```{r config}
repo_dir <- "~/komodo_research"
proj_dir <- file.path(repo_dir, 'projects', 'ash_2022')
lib_dir <- file.path(repo_dir, 'library')
code_dir <- file.path(proj_dir, 'code')
model_dir <- file.path(proj_dir, 'model')
plot_dir <- file.path(proj_dir, 'plot')
dir.create(code_dir, showWarnings = F)
dir.create(model_dir, showWarnings = F)
dir.create(plot_dir, showWarnings = F)

library(tidyverse)
library(glue)
library(clipr)
library(tictoc)
library(DBI)
library(googlesheets4)
library(googledrive)
library(MatchIt)
library(table1)
library(cobalt)
library(boot)
library(parallel)
source(file.path(lib_dir, "R/utils.R"))
source(file.path(lib_dir, "R/sql_helper.R"))
source(file.path(lib_dir, "R/sql_utils.R"))
```

```{r connection}
# create ODBC connection
con_odbc <- DBI::dbConnect(
  odbc::odbc(), "snowflake", 
  role = "ANALYST", 
  warehouse = "LARGE_WH"
)

execute_sql("USE DATABASE SANDBOX_KOMODO;")
execute_sql("USE SCHEMA AYWEI;")
execute_sql("USE ROLE ANALYST;")
execute_sql("USE WAREHOUSE XLARGE_WH;")
```

```{r gsconnection}
# google sheet auth
gs4_auth(
  email = gargle::gargle_oauth_email(),
  path = NULL,
  scopes = "https://www.googleapis.com/auth/spreadsheets",
  cache = gargle::gargle_oauth_cache(),
  use_oob = gargle::gargle_oob_default(),
  token = gargle::token_fetch("https://www.googleapis.com/auth/spreadsheets")
)
code_list_ss = "1lwGATVIUxa1RMtcfUmpZRoJLEcDadBboyTmTthN2U20"
output_ss = "1Vs8wMBUndpKMF1jx_PVWZskhREAGYaJUudteNMNvviM"

proj_drive_url = "https://drive.google.com/drive/folders/1Dfs8-sJUgx-5rfbLJIY2igNIpPJ4rsX-"
proj_drive = drive_get(path = proj_drive_url)
#drive_mkdir('plot', path = proj_drive, overwrite = FALSE)
plot_drive = drive_ls(proj_drive, 'plot')
```

```{r project_spec}
## Table reference
rx_version = '20220613'
mx_version = '20220605'
code_version = '20220606'
query_start_date = '2018-12-01'
query_end_date = '2022-12-31'
## Output table names
prefix = 'SCD'
cci_def = glue("MAP_VOCABULARY.RXNORM_{code_version}.CHARLSON_CODE")
cci_score = glue("MAP_VOCABULARY.RXNORM_{code_version}.CHARLSON_SCORE")
```

## Prepare Code Definition

```{r code_list}
# create a code list for scd, voc
voc_diag_sql = get_code(c('D570%', 'D5721%', 'D5741%', 'D5743%', 'D5745%', 'D5781%'), method = 'pattern', type = 'diag')
scd_diag_sql = get_code(c('D570%', 'D571%', 'D572%', 'D574%', 'D578%'), method = 'pattern', type = 'diag')
print(voc_diag <- read_query(voc_diag_sql))
print(scd_diag <- read_query(scd_diag_sql))
sheet_write(voc_diag, ss = code_list_ss, sheet = 'voc')
sheet_write(scd_diag, ss = code_list_ss, sheet = 'scd')
```

```{r code_list2}
# search all NDCs
oxbryta_ndc_sql = get_code(c('oxbryta'), method = 'name', type = 'ndc')
hydroxyurea_ndc_sql = get_code(c('hydroxyurea'), method = 'name', type = 'ndc')
adakveo_ndc_sql = get_code(c('adakveo'), method = 'name', type = 'ndc')
endari_ndc_sql = get_code(c('endari'), method = 'name', type = 'ndc')

print(oxbryta_ndc <- read_query(oxbryta_ndc_sql))
print(hydroxyurea_ndc <- read_query(hydroxyurea_ndc_sql))
print(adakveo_ndc <- read_query(adakveo_ndc_sql))
print(endari_ndc <- read_query(endari_ndc_sql))

sheet_write(oxbryta_ndc, ss = code_list_ss, sheet = 'oxbryta')
sheet_write(hydroxyurea_ndc, ss = code_list_ss, sheet = 'hydroxyurea')
sheet_write(adakveo_ndc, ss = code_list_ss, sheet = 'adakveo')
sheet_write(endari_ndc, ss = code_list_ss, sheet = 'endari')
```
```{r code_list3}
cci = read_query(glue("SELECT * FROM {cci_def};"))
sheet_write(cci, ss = code_list_ss, sheet = 'cci')
cci2 = read_query(glue("SELECT * FROM {cci_score};"))
sheet_write(cci2, ss = code_list_ss, sheet = 'cci_score')
transfusion = range_speedread(code_list_ss, sheet = 'transfusion')
colnames(transfusion) <- tolower(colnames(transfusion))
print(cci)
print(cci2)
print(transfusion)
```

```{r code_list4}
# create code lists:
# code_list will be queried from the whole DB
# subsample_code_list will be searched within a small list of patients
code_list <- 
  bind_rows(
    voc_diag %>% select(code, code_description) %>% mutate(codetype = "ICD10CM", event = "voc"),
    scd_diag %>% select(code, code_description) %>% mutate(codetype = "ICD10CM", event = "scd"),
    oxbryta_ndc %>% select(ndc, cui_l1_name) 
      %>% rename(code = ndc, code_description = cui_l1_name) 
      %>% mutate(codetype = "NDC", event = "oxbryta"),
    hydroxyurea_ndc %>% select(ndc, cui_l1_name) 
      %>% rename(code = ndc, code_description = cui_l1_name) 
      %>% mutate(codetype = "NDC", event = "hydroxyurea"),
    adakveo_ndc %>% select(ndc, cui_l1_name) 
      %>% rename(code = ndc, code_description = cui_l1_name) 
      %>% mutate(codetype = "NDC", event = "adakveo"),
    endari_ndc %>% select(ndc, cui_l1_name) 
      %>% rename(code = ndc, code_description = cui_l1_name) 
      %>% mutate(codetype = "NDC", event = "endari")
  )

sheet_write(code_list, ss = code_list_ss, sheet = 'code_list')

subsample_code_list <-
  bind_rows(
    transfusion %>% select(code, codetype, code_description) %>% mutate(event = 'transfusion'),
    cci %>% select(icd, charlson_category) %>%
      rename(code = icd, code_description = charlson_category) %>%
      mutate(codetype = 'ICD10CM', event = 'cci') %>%
      select(code, codetype, code_description, event)
  )
sheet_write(subsample_code_list, ss = code_list_ss, sheet = 'subsample_code_list')

write_csv(code_list, file = file.path(code_dir, "code_list.csv"))
write_csv(subsample_code_list, file = file.path(code_dir, "subsample_code_list.csv"))
```

```{r upload_code_list}
bulk_upload(
  conn = con_odbc,
  dir = code_dir,
  filename = "code_list.csv", 
  stage_name = "stage_kr",
  table_full_name = "SANDBOX_KOMODO.AYWEI.SCD_CODE_LIST",
  create_stage = FALSE,
  database = 'SANDBOX_KOMODO',
  role = 'ANALYST',
  warehouse = 'LARGE_WH',
  save_sql = TRUE,
  run_sql = TRUE,
  snowsql_profile = 'ywei'
)

bulk_upload(
  conn = con_odbc,
  dir = code_dir,
  filename = "subsample_code_list.csv", 
  stage_name = "stage_kr",
  table_full_name = "SANDBOX_KOMODO.AYWEI.SCD_CODE_LIST_SUB",
  create_stage = FALSE,
  database = 'SANDBOX_KOMODO',
  role = 'ANALYST',
  warehouse = 'LARGE_WH',
  save_sql = TRUE,
  run_sql = TRUE,
  snowsql_profile = 'ywei'
)
```

## Create Study Eligible Cohort

```{r step_0_get_ce}
# build CE table for all patients
# optional, use ce_{mx_version} file
# sql_split_fun = get_sql_split_fun(grace_period = grace_period)
# execute_sql(sql_split_fun)
# tic("CE")
# sql = glue("  
#     create or replace table ce_{mx_version} as
#     {get_ce(mx_version = mx_version, grace_period = 45)}
#     ;
# ")
# execute_sql(sql)
# toc()
```

```{r step_1_get_query}
# build encounter tables for the study
code_list_table = glue('{prefix}_code_list')
code_list_sub_table = glue('{prefix}_code_list_sub')
tic("Mx Encounter")
sql_mx = glue("
    create or replace table {prefix}_mx_encounter as
    {query_event_mx(
      code_list_table = code_list_table,
      mx_version = mx_version,
      start_date = query_start_date, end_date = query_end_date
      )
    }
    ;
")
execute_sql(sql_mx)
toc()

tic("Rx Encounter")
sql_rx = glue("
    create or replace table {prefix}_rx_encounter as
    {query_event_rx(
      code_list_table = code_list_table,
      rx_version = rx_version,
      start_date = query_start_date, end_date = query_end_date
      )
    }
    ;
")
execute_sql(sql_rx)
toc()
```


```{r step_2_build_oxbryta_cohort}
sql = glue("  
    create or replace table {prefix}_oxbryta_cohort as
    with query as (
      select upk_key2, claim_date, code, codetype
      from {prefix}_rx_encounter where event = 'oxbryta'
    )
    select upk_key2, claim_date as index_date, code, codetype
    from query
    qualify row_number() over(partition by upk_key2 order by claim_date) = 1
    ;
")
execute_sql(sql)
# 
# print(read_query(glue("select year(index_date) as year, count(*) as n from {prefix}_oxbryta_cohort group by year order by year")))
# print(read_query(glue("select source, code, count(*) as n from {prefix}_oxbryta_cohort group by source, code")))
# print(read_query(glue("select min(index_date) from {prefix}_oxbryta_cohort")))
```

```{r step_3_build_control_cohort}
seed = 1234
sql = glue("
  create or replace table {prefix}_control_cohort as
  select upk_key2, start_date, end_date, 
    greatest(start_date + 365, to_date('2019-12-01')) as first_index_date,
    e.end_date - 365 as last_index_date,
    last_index_date - first_index_date as length,
    uniform(0::float, 1::float, random({seed})) as rng,
    first_index_date + (length * rng)::int as index_date
  from ce_{mx_version} e
  where e.end_date - e.start_date >= 730 
    and e.upk_key2 in (select upk_key2 from {prefix}_mx_encounter where event = 'scd')
    and e.upk_key2 not in (select upk_key2 from {prefix}_oxbryta_cohort)
    and e.end_date >= to_date('2018-12-01') + 730
    and length > 0
  ;
")
execute_sql(sql)
# 
#   with query as (
#     select upk_key2, claim_date, code, codetype
#     from {prefix}_mx_encounter 
#     where event = 'scd' and upk_key2 not in (select upk_key2 from {prefix}_oxbryta_cohort)
#   ),
#   first_claim as(
#     select upk_key2, claim_date, code, codetype,
#       row_number() over(partition by upk_key2 order by claim_date) as n
#     from query
#     qualify row_number() over(partition by upk_key2 order by claim_date) = 1
#   )
#   select c.upk_key2, c.claim_date, 
#     greatest(start_date + 365, c.claim_date + 1, to_date('2019-12-01')) as first_index_date,
#     e.end_date - 365 as last_index_date,
#     last_index_date - first_index_date as length,
#     uniform(0::float, 1::float, random({seed})) as rng,
#     first_index_date + (length * rng)::int as index_date
#   from first_claim c
#   inner join ce_{mx_version} e
#   on c.upk_key2 = e.upk_key2 and c.claim_date between e.start_date and e.end_date - 365
#   where e.end_date - e.start_date >= 730 and length > 0
```


```{r step_4_combine_cohort_and_add_flag}
bene_table = glue("MAP_ENCOUNTERS.MX_ENCOUNTERS_{mx_version}.BENEFICIARY_LS_GA")
sql = glue("
  create or replace table {prefix}_combined_cohort as
  with combined as (
    select upk_key2, index_date, 'oxbryta' as cohort
    from {prefix}_oxbryta_cohort
    union
    select upk_key2, index_date, 'control' as cohort
    from {prefix}_control_cohort
  ),
  elig as (
    select c.upk_key2, count(*) as elig
    from combined c
    inner join ce_{mx_version} e
    on c.upk_key2 = e.upk_key2 
      and c.index_date - 365 between e.start_date and e.end_date
      and c.index_date + 365 between e.start_date and e.end_date
    group by c.upk_key2
  ),
  scd as (
    select c.upk_key2, count(*) as n_scd_before
    from combined c
    inner join {prefix}_mx_encounter m
    on c.upk_key2 = m.upk_key2 
      and m.event = 'scd'
      and m.claim_date between c.index_date - 365 and c.index_date
    group by c.upk_key2
  ),
  excl as (
    select c.upk_key2, 
      count_if(r.event = 'adakveo') as n_adakveo,
      count_if(r.event = 'endari') as n_endari
    from combined c
    inner join {prefix}_rx_encounter r
    on c.upk_key2 = r.upk_key2 and r.event in ('adakveo', 'endari')
    group by c.upk_key2 
  ),
  bene as (
    select distinct c.upk_key2,
      first_value(patient_dob) over (partition by c.upk_key2 order by patient_dob nulls last) as patient_dob,
      first_value(patient_gender) over (partition by c.upk_key2 order by patient_gender nulls last) as patient_gender,
      first_value(patient_state) over (partition by c.upk_key2 order by patient_state nulls last) as patient_state,
      first_value(patient_zip) over (partition by c.upk_key2 order by patient_zip nulls last) as patient_zip
    from combined c
    left join {bene_table} b
    on c.upk_key2 = b.upk_key2 and c.index_date between b.closed_start_date and b.closed_end_date
  )
  select distinct c.upk_key2, cohort, index_date, 
    coalesce(elig, 0) as elig, 
    coalesce(n_scd_before, 0) as n_scd_before,
    patient_dob, patient_gender, patient_state, patient_zip,
    year(index_date) - year(patient_dob) as age
    --coalesce(n_adakveo, 0) as n_adakveo, 
    --coalesce(n_endari, 0) as n_endari
  from combined c
  left join elig e
  on c.upk_key2 = e.upk_key2 
  left join scd m
  on c.upk_key2 = m.upk_key2
  left join excl r
  on c.upk_key2 = r.upk_key2
  left join bene b
  on c.upk_key2 = b.upk_key2
  ;
")
execute_sql(sql)
```


```{r step_5_final_cohort}
sql = glue("
  create or replace table {prefix}_final_cohort as
  select *
  from {prefix}_combined_cohort
  where elig > 0 and n_scd_before > 0 and age >= 12
  ;
")
execute_sql(sql)
```

```{r step_6_cohort_funnel}
select_str = "cohort, count(distinct upk_key2) as n_bene"

sql = glue("
    select 'a. all users in study window' as criteria, 'oxbryta' as cohort, count(distinct upk_key2) as n_bene
    from {prefix}_oxbryta_cohort
    
    union all
    select 'a. all users in study window' as criteria, 'control' as cohort, count(distinct upk_key2) as n_bene  
    from {prefix}_mx_encounter
    where event = 'scd'
    
    union all
    select 'b. continuous enrollment' as criteria, {select_str}
    from {prefix}_combined_cohort
    where elig > 0
    group by cohort

    union all
    select 'c. w/ sickle-cell disease diagnosis' as criteria, {select_str}
    from {prefix}_combined_cohort
    where elig > 0 and n_scd_before > 0
    group by cohort

    union all
    select 'd. age >= 12 on index date' as criteria, {select_str}
    from {prefix}_combined_cohort
    where elig > 0 and n_scd_before > 0 and age >= 12
    group by cohort
    
    order by cohort, criteria
  ;
")
print(cohort_funnel <- read_query(sql))
```

```{r step_7_more_encounters}
# create encounter table for covariates and outcome
code_list_table = glue('{prefix}_code_list')
code_list_sub_table = glue('{prefix}_code_list_sub')
patient_table = glue("{prefix}_combined_cohort")
tic("Mx Encounter")
sql_mx = glue("
    create or replace table {prefix}_mx_encounter_sub as
    {query_event_mx(
      code_list_table = code_list_sub_table,
      patient_table = patient_table,
      mx_version = mx_version,
      start_date = query_start_date, end_date = query_end_date
      )
    }
    ;
")
execute_sql(sql_mx)
toc()
```

```{r clean_voc_inpatient_stays}
ip_allowable_gap = 2
# 0 means allow consecutive stays not merge, so 9/1-9/15 and 9/16-9/30
# 1 means gap should be at least one full day, so 9/1-9/15 and 9/17-9/30
sql = glue("
    create or replace table {prefix}_voc_ip_stay as
    with voc_data as(
      select distinct
        upk_key2, visit_start_date, visit_end_date
      from {prefix}_mx_encounter
      where event = 'voc' and visit_setting_of_care = 'Inpatient Visit'
    ),
    gap as (
        -- construct a gap dataset. The arbitrary early date does not matter.
        select upk_key2, '1970-01-01' as gap_start_date, min(visit_start_date -1) as gap_end_date
        from voc_data
        group by upk_key2
        union all
        select upk_key2,
            max(visit_end_date + 1) over (partition by upk_key2 order by visit_start_date) as gap_start_date,
            lead(visit_start_date - 1) over (partition by upk_key2 order by visit_start_date) as gap_end_date
        from voc_data qualify gap_end_date - gap_start_date + 1 >= {ip_allowable_gap}
        union all
        select upk_key2, max(visit_end_date + 1) as gap_start_date, null as gap_end_date
        from voc_data
        group by upk_key2
    )
    select
        upk_key2,
        gap_end_date + 1 as visit_start_date,
        lead(gap_start_date -1) over (partition by upk_key2 order by gap_start_date) as visit_end_date,
        'Inpatient Visit' as visit_setting_of_care
    from gap qualify gap_end_date IS NOT null
    ;
")
execute_sql(sql)

```

```{r step_8_get_covariates}
sql = glue("
    create or replace table {prefix}_final_cohort_w_cov as
    with 
    voc_data as(
      select distinct
        upk_key2, visit_setting_of_care, 
          coalesce(visit_start_date, claim_date) as visit_start_date,
          coalesce(visit_end_date, claim_date) as visit_end_date
      from {prefix}_mx_encounter
      where event = 'voc' and visit_setting_of_care != 'Inpatient Visit'
      union
      select upk_key2, visit_setting_of_care, visit_start_date, visit_end_date
      from {prefix}_voc_ip_stay
    ),
    voc as (
      select a.upk_key2,
        count(distinct case when 
          b.visit_start_date between a.index_date - 365 and a.index_date 
          then visit_start_date else null end
        ) as n_pre_voc,
        count(distinct case when 
          b.visit_start_date between a.index_date - 365 and a.index_date 
          and visit_setting_of_care = 'Inpatient Visit'
          then visit_start_date else null end
        ) as n_pre_voc_ip,
        count(distinct case when 
          b.visit_start_date between a.index_date - 365 and a.index_date 
          and visit_setting_of_care = 'Emergency Room Visit'
          then visit_start_date else null end
        ) as n_pre_voc_er,
        count(distinct case when 
          b.visit_start_date between a.index_date - 365 and a.index_date 
          and visit_setting_of_care in ('Inpatient Visit', 'Emergency Room Visit')
          then visit_start_date else null end
        ) as n_pre_voc_iper,
        
        count(distinct case when 
          b.visit_start_date between a.index_date + 1 and a.index_date + 365 
          then visit_start_date else null end
        ) as n_post_voc,
        count(distinct case when 
          b.visit_start_date between a.index_date + 1 and a.index_date + 365 
          and visit_setting_of_care = 'Inpatient Visit'
          then visit_start_date else null end
        ) as n_post_voc_ip,
        count(distinct case when 
          b.visit_start_date between a.index_date + 1 and a.index_date + 365 
          and visit_setting_of_care = 'Emergency Room Visit'
          then visit_start_date else null end
        ) as n_post_voc_er,
        count(distinct case when 
          b.visit_start_date between a.index_date + 1 and a.index_date + 365
          and visit_setting_of_care in ('Inpatient Visit', 'Emergency Room Visit')
          then visit_start_date else null end
        ) as n_post_voc_iper
      from {prefix}_final_cohort a
      inner join voc_data b
      on a.upk_key2 = b.upk_key2 and b.visit_start_date between a.index_date - 365 and a.index_date + 365
      where visit_start_date < '2030-12-31'
      group by a.upk_key2
    ),
    transfusion as (
      select a.upk_key2,
        count(distinct claim_date) as n_transfusion
      from {prefix}_final_cohort a
      inner join {prefix}_mx_encounter_sub b
      on a.upk_key2 = b.upk_key2 and b.claim_date between a.index_date - 365 and a.index_date
      where event = 'transfusion'
      group by a.upk_key2
    ),
    drugs as (
      select a.upk_key2, 
        count_if(event = 'hydroxyurea') as n_hydroxyurea,
        count_if(event = 'adakveo') as n_adakveo,
        count_if(event = 'endari') as n_endari,
        count(*) as n_voc_treatment
      from {prefix}_final_cohort a
      inner join {prefix}_rx_encounter b
      on a.upk_key2 = b.upk_key2 and b.claim_date between a.index_date - 365 and a.index_date
      where event in ('hydroxyurea', 'adakveo', 'endari')
      group by a.upk_key2
    ),
    cci_data as(
      select distinct a.upk_key2, c.charlson_category
      from {prefix}_final_cohort a
      inner join {prefix}_mx_encounter_sub b
      on a.upk_key2 = b.upk_key2 and b.claim_date between a.index_date - 365 and a.index_date
      inner join {cci_def} c
      on b.code = c.icd
      where event = 'cci'
      union
      select upk_key2, case 
          when age < 50 then '< 50'
          when age < 60 then '50-59'
          when age < 70 then '60-69'
          when age < 80 then '70-79'
          when age >= 80 then '80+'
          else '< 50'
      end as charlson_category
      from {prefix}_final_cohort
    ),
    cci as(
      select upk_key2, sum(charlson_score) as charlson_score
      from cci_data a
      inner join {cci_score} d
      on a.charlson_category = d.charlson_category
      group by upk_key2
    )
    select c.*,
      coalesce(n_hydroxyurea, 0) as n_hydroxyurea,
      coalesce(n_adakveo, 0) as n_adakveo,
      coalesce(n_endari, 0) as n_endari,
      coalesce(n_voc_treatment, 0) as n_voc_treatment,
      
      coalesce(n_pre_voc, 0) as n_pre_voc,
      coalesce(n_pre_voc_ip, 0) as n_pre_voc_ip,
      coalesce(n_pre_voc_er, 0) as n_pre_voc_er,
      coalesce(n_pre_voc_iper, 0) as n_pre_voc_iper,
      
      coalesce(n_post_voc, 0) as n_post_voc,
      coalesce(n_post_voc_ip, 0) as n_post_voc_ip,
      coalesce(n_post_voc_er, 0) as n_post_voc_er,
      coalesce(n_post_voc_iper, 0) as n_post_voc_iper,      
      
      case
        when age < 20 then '1. 12-19'
        when age < 30 then '2. 20-29'
        when age < 40 then '3. 30-39'
        when age < 50 then '4. 40-49'
        when age < 70 then '5. 50-69'
        when age >= 70 then '9. 70+'
        else 'Missing'
      end as age_cat,
      case
        when patient_gender = 'F' then 'Female'
        when patient_gender = 'M' then 'Male'
        else 'Missing'
      end as gender,
      case
        when patient_state in ('CT', 'ME', 'MA', 'NH', 'RI', 
                             'VT', 'NJ', 'NY', 'PA') then '1. Northeast'
        when patient_state in ('IL', 'IN', 'MI', 'OH', 'WI', 
                             'IA', 'KS', 'MO', 'MN', 'NE', 'ND',
                             'SD') then '2. Midwest'
        when patient_state in ('DE', 'FL', 'GA', 'MD', 'NC', 
                             'SC', 'VA', 'DC', 'WV', 'AL',
                             'KY', 'MS', 'TN', 'AR', 'LA',
                             'OK', 'TX') then '3. South'
        when patient_state in ('AZ', 'CO', 'ID', 'MT', 'NV', 
                             'NM', 'UT', 'WY', 'AK', 'CA',
                             'HI', 'OR', 'WA') then '4. West'
        when patient_state in ('PR', 'VI') then '5. US Territories'
        else 'Missing'
      end as region,
      year(index_date) as year,
      case
        when coalesce(charlson_score, 0) < 5 then to_char(coalesce(charlson_score, 0))
        when coalesce(charlson_score, 0) >=5 then '5+'
      end as cci,
      case
        when coalesce(n_transfusion, 0) < 5 then to_char(coalesce(n_transfusion, 0))
        else '5+'
      end as transfusion,
      coalesce(n_voc_treatment, 0) > 0 as voc_treatment,
      case
        when coalesce(n_pre_voc, 0) < 5 then to_char(coalesce(n_pre_voc, 0))
        else '5+'
      end as pre_voc,
      case
        when coalesce(n_pre_voc_ip, 0) < 5 then to_char(coalesce(n_pre_voc_ip, 0))
        else '5+'
      end as pre_voc_ip,
      case
        when coalesce(n_pre_voc_er, 0) < 5 then to_char(coalesce(n_pre_voc_er, 0))
        else '5+'
      end as pre_voc_er,
      case
        when coalesce(n_pre_voc_iper, 0) < 5 then to_char(coalesce(n_pre_voc_iper, 0))
        else '5+'
      end as pre_voc_iper,
      case
        when coalesce(n_post_voc, 0) < 5 then to_char(coalesce(n_post_voc, 0))
        else '5+'
      end as post_voc,
      case
        when coalesce(n_post_voc_ip, 0) < 5 then to_char(coalesce(n_post_voc_ip, 0))
        else '5+'
      end as post_voc_ip,
      case
        when coalesce(n_post_voc_er, 0) < 5 then to_char(coalesce(n_post_voc_er, 0))
        else '5+'
      end as post_voc_er,
      case
        when coalesce(n_post_voc_iper, 0) < 5 then to_char(coalesce(n_post_voc_iper, 0))
        else '5+'
      end as post_voc_iper
    from {prefix}_final_cohort c
    left join voc v
    on c.upk_key2 = v.upk_key2
    left join transfusion t
    on c.upk_key2 = t.upk_key2
    left join drugs d
    on c.upk_key2 = d.upk_key2
    left join cci i
    on c.upk_key2 = i.upk_key2
    ;
")
execute_sql(sql)
```

```{r step_9_download_to_local}
cohort <- 
  tbl(con_odbc, Id(database = "SANDBOX_KOMODO", schema = "AYWEI", table = "SCD_FINAL_COHORT_W_COV")
) %>% collect()
colnames(cohort) <- tolower(colnames(cohort))
```

```{r step_10_cohort_funnal}
cohort_funnel_reshape <-
  cohort_funnel %>% 
  arrange(criteria, cohort) %>% 
  pivot_wider(id_cols = "criteria", names_from = c("cohort"), values_from = c("n_bene")) %>%
  mutate(pct_oxbryta = oxbryta/max(oxbryta), pct_control = control/max(control)) %>%
  select(criteria, oxbryta, pct_oxbryta, control, pct_control)
print(cohort_funnel_reshape)
sheet_write(cohort_funnel_reshape, ss = output_ss, sheet = 'cohort_funnel')
```

```{r step_11_cohort_summary}
cohort <- cohort %>% 
  mutate(
    year_quarter = paste0(year, quarters(index_date)), 
    cohort = factor(cohort, levels = c("oxbryta", "control")),
    region = factor(region))
covariates <- get_covariates(
  cohort, 
  covariates = 
    c('age_cat', 'gender', 'region', 'patient_state', 'year_quarter', 'voc_treatment', 'cci', 'transfusion', 
      'pre_voc', 'pre_voc_ip', 'pre_voc_er', 'pre_voc_iper', 
      'post_voc', 'post_voc_ip', 'post_voc_er', 'post_voc_iper'))
print(covariates$tbl_bal)
sheet_write(covariates$tbl_bal, ss = output_ss, sheet = 'covariates')

pre_matching <- cohort %>% 
  filter(age < 70, !region %in% c('5. US Territories', 'Missing')) %>%
  mutate(
        cohort_name = cohort,
        cohort = as.numeric(cohort == 'oxbryta'),
        region = factor(region), age_cat = factor(age_cat), 
         gender = factor(gender), year_quarter = factor(year_quarter),
         transfusion = factor(transfusion), cci = factor(cci), voc_treatment = factor(voc_treatment))

covariates_pre_matching <- get_covariates(
  pre_matching, 
  covariates = 
    c('age_cat', 'gender', 'region', 'year_quarter', 'voc_treatment', 'cci', 'transfusion', 
      'pre_voc', 'pre_voc_ip', 'pre_voc_er', 'pre_voc_iper', 
      'post_voc', 'post_voc_ip', 'post_voc_er', 'post_voc_iper'))
print(covariates_pre_matching$tbl_bal)
sheet_write(covariates_pre_matching$tbl_bal, ss = output_ss, sheet = 'pre_matching')

# cohort %>% group_by(cohort) %>% summarize(max(n_pre_voc_ip))
# cohort %>% filter(n_pre_voc_ip == 26)

```

```{r matching_design_1}
matching_model_1 <- run_matching(seed = 1234, pre_matching,
                                matching_vars = c('age_cat', 'gender', 'region', 'cci', 'year_quarter', 'transfusion', 'voc_treatment'),
                                exact_matching_vars = NULL,
                                summary_vars = NULL,
                                caliper = 0.1)
saveRDS(matching_model_1, file.path(model_dir, paste0("matching_model_1.Rds")))
matching_model_1 <- readRDS(file.path(model_dir, paste0("matching_model_1.Rds")))

sheet_write(matching_model_1$bal_nn, ss = output_ss, sheet = 'matching_nn')
sheet_write(matching_model_1$bal_tbl, ss = output_ss, sheet = 'matching_bal')
print(matching_model_1$bal_nn)
print(matching_model_1$bal_tbl)
print(matching_model_1$bal_plot)
print(matching_model_1$love_plot)

ggsave(matching_model_1$bal_plot, filename = file.path(plot_dir, 'bal_plot_model_1.png'), width = 6, height = 4)
ggsave(matching_model_1$love_plot, filename = file.path(plot_dir, 'love_plot_model_1.png'), width = 10, height = 20)
drive_plot1 <- drive_upload(file.path(plot_dir, 'bal_plot_model_1.png'), path = plot_drive, overwrite = T)
drive_plot2 <- drive_upload(file.path(plot_dir, 'love_plot_model_1.png'), path = plot_drive, overwrite = T)
# add link to worksheet: not working
# url_plot1 <- drive_link(drive_plot1)
# url_plot2 <- drive_link(drive_plot2)
# sheet_write(data.frame(gs4_formula(glue("=IMAGE(\"{url_plot1}\")"))), ss = output_ss, sheet = "ps_plot")
# need to semi manually insert into worksheets.

post_matching_1 <- match.data(matching_model_1$matching_model)
```


```{r matching_design_1_summary}
post_matching_1_long <- post_matching_1 %>% select(cohort_name, n_pre_voc_ip, n_post_voc_ip, n_pre_voc_er, n_post_voc_er) %>%
  pivot_longer(cols = c("n_pre_voc_ip", "n_post_voc_ip", "n_pre_voc_er", "n_post_voc_er"), 
               names_to = "variable", values_to = "count") %>%
  mutate(treat = as.numeric(cohort_name == 'oxbryta'), 
         post = as.numeric(variable %in% c('n_post_voc_ip', 'n_post_voc_er')),
         outcome = stringr::str_extract(variable, '[a-z]*$'))
hist <- ggplot(post_matching_1_long) + geom_histogram(aes(x = count, fill = variable), position = "dodge", binwidth = 1) + facet_grid(outcome~cohort_name) + coord_cartesian(xlim=c(0, 20))
print(hist)
ggsave(hist, filename = file.path(plot_dir, 'histogram_model_1.png'), width = 6, height = 5)
drive_plot3 <- drive_upload(file.path(plot_dir, 'histogram_model_1.png'), path = plot_drive, overwrite = T)

summ <- post_matching_1_long %>% group_by(outcome, treat, post) %>%
  summarize(n = n(), mean = mean(count), voc1p = sum(count >= 1), voc2p = sum(count >= 2), voc3p = sum(count >= 3))

sheet_write(summ, ss = output_ss, sheet = 'outcome_summary')

```

```{r matching_design_1_modeling}
ip_model <- glm(count ~ treat*post, family = poisson(link = 'identity'), data = post_matching_1_long %>% filter(outcome == 'ip'))
er_model <- glm(count ~ treat*post, family = poisson(link = 'identity'), data = post_matching_1_long %>% filter(outcome == 'er'))
ip_model_1p <- lm(I(count>=1) ~ treat*post, data = post_matching_1_long %>% filter(outcome == 'ip'))
er_model_1p <- lm(I(count>=1) ~ treat*post, data = post_matching_1_long %>% filter(outcome == 'er'))
ip_model_2p <- lm(I(count>=2) ~ treat*post, data = post_matching_1_long %>% filter(outcome == 'ip'))
er_model_2p <- lm(I(count>=2) ~ treat*post, data = post_matching_1_long %>% filter(outcome == 'er'))
ip_model_3p <- lm(I(count>=3) ~ treat*post, data = post_matching_1_long %>% filter(outcome == 'ip'))
er_model_3p <- lm(I(count>=3) ~ treat*post, data = post_matching_1_long %>% filter(outcome == 'er'))

```

```{r matching_design_1_boot_ci}
fit_did <- function(data_wide, ind) {
  data_long <- 
    data_wide[ind,] %>% 
    select(cohort_name, n_pre_voc_ip, n_post_voc_ip, n_pre_voc_er, n_post_voc_er) %>%
    pivot_longer(cols = c("n_pre_voc_ip", "n_post_voc_ip", "n_pre_voc_er", "n_post_voc_er"), 
                 names_to = "variable", values_to = "count") %>%
    mutate(treat = as.numeric(cohort_name == 'oxbryta'), 
           post = as.numeric(variable %in% c('n_post_voc_ip', 'n_post_voc_er')),
           outcome = stringr::str_extract(variable, '[a-z]*$'))
  
  ip_model <- glm(count ~ treat*post, family = poisson(link = 'identity'), data = data_long %>% filter(outcome == 'ip'))
  er_model <- glm(count ~ treat*post, family = poisson(link = 'identity'), data = data_long %>% filter(outcome == 'er'))
  ip_model_1p <- lm(I(count>=1) ~ treat*post, data = data_long %>% filter(outcome == 'ip'))
  er_model_1p <- lm(I(count>=1) ~ treat*post, data = data_long %>% filter(outcome == 'er'))
  ip_model_2p <- lm(I(count>=2) ~ treat*post, data = data_long %>% filter(outcome == 'ip'))
  er_model_2p <- lm(I(count>=2) ~ treat*post, data = data_long %>% filter(outcome == 'er'))
  ip_model_3p <- lm(I(count>=3) ~ treat*post, data = data_long %>% filter(outcome == 'ip'))
  er_model_3p <- lm(I(count>=3) ~ treat*post, data = data_long %>% filter(outcome == 'er'))

  c(coef(ip_model)['treat:post'], coef(er_model)['treat:post'],
    coef(ip_model_1p)['treat:post'], coef(er_model_1p)['treat:post'],
    coef(ip_model_2p)['treat:post'], coef(er_model_2p)['treat:post'],
    coef(ip_model_3p)['treat:post'], coef(er_model_3p)['treat:post'])
}
fit_did(post_matching_1)
cl <- makeCluster(detectCores())
res <- boot(post_matching_1, fit_did, R = 1000, parallel = "snow", cl = cl)
stopCluster(cl)
ci <- t(sapply(1:8, function(i) boot.ci(res, type = c('basic'), index = i)$basic[c(4,5)]))

model_df <- data.frame(
  model = rep(c('counts', 'voc>=1', 'voc>=2', 'voc>=3'), each = 2),
  outcome = rep(c('ip', 'er'), 4), 
  rbind(coef(ip_model), coef(er_model), coef(ip_model_1p), coef(er_model_1p), 
        coef(ip_model_2p), coef(er_model_2p), coef(ip_model_3p), coef(er_model_3p)),
  lower = ci[,1],
  upper = ci[,2]
  )

# sheet_add(ss = output_ss, 'did_model')
range_write(model_df, ss = output_ss, sheet = 'did_model', range = 'A1')
```

```{r matching_design_2}
pre_matching_2 <- pre_matching %>%
  mutate(pre_voc_ip2 = case_when(
    n_pre_voc_ip == 0 ~ '0',
    n_pre_voc_ip == 1 ~ '1',
    n_pre_voc_ip == 2 ~ '2',
    n_pre_voc_ip == 3 ~ '3',
    n_pre_voc_ip == 4 ~ '4',
    n_pre_voc_ip == 5 ~ '5',
    n_pre_voc_ip <= 10 ~ '6-10',
    TRUE ~ '11+'
  ),
  pre_voc_er2 = case_when(
    n_pre_voc_er == 0 ~ '0',
    n_pre_voc_er == 1 ~ '1',
    n_pre_voc_er == 2 ~ '2',
    n_pre_voc_er == 3 ~ '3',
    n_pre_voc_er == 4 ~ '4',
    n_pre_voc_er == 5 ~ '5',
    n_pre_voc_er <= 10 ~ '6-10',
    TRUE ~ '11+')
  ) %>%
  filter(!(year_quarter %in% c('2019Q4', '2021Q3')))

matching_model_2 <- run_matching(seed = 1234, pre_matching_2,
                                matching_vars = c('age_cat', 'gender', 'region', 'cci', 'year_quarter', 'transfusion', 'voc_treatment', 'pre_voc_er2', 'pre_voc_ip2'),
                                exact_matching_vars = 'voc_treatment',
                                summary_vars = NULL,
                                caliper = 0.1)
saveRDS(matching_model_2, file.path(model_dir, paste0("matching_model_2.Rds")))
matching_model_2 <- readRDS(file.path(model_dir, paste0("matching_model_2.Rds")))

sheet_write(matching_model_2$bal_nn, ss = output_ss, sheet = 'matching_nn_2')
sheet_write(matching_model_2$bal_tbl, ss = output_ss, sheet = 'matching_bal_2')
print(matching_model_2$bal_nn)
print(matching_model_2$bal_tbl)
print(matching_model_2$bal_plot)
print(matching_model_2$love_plot)

ggsave(matching_model_2$bal_plot, filename = file.path(plot_dir, 'bal_plot_model_2.png'), width = 6, height = 4)
ggsave(matching_model_2$love_plot, filename = file.path(plot_dir, 'love_plot_model_2.png'), width = 10, height = 20)
drive_plot1 <- drive_upload(file.path(plot_dir, 'bal_plot_model_2.png'), path = plot_drive, overwrite = T)
drive_plot2 <- drive_upload(file.path(plot_dir, 'love_plot_model_2.png'), path = plot_drive, overwrite = T)

post_matching_2 <- match.data(matching_model_2$matching_model)
```

```{r matching_design_2_investigation}
pre_matching_2 %>% group_by(cohort, voc_treatment) %>%
  summarize(n = n(), mean(n_pre_voc_ip), mean(n_post_voc_ip))

post_matching_2 %>% group_by(cohort, voc_treatment) %>%
  summarize(n = n(), mean(n_pre_voc_ip), mean(n_post_voc_ip))
```

```{r matching_design_2_summary}
post_matching_2_long <- post_matching_2 %>% 
  select(cohort_name, n_pre_voc_ip, n_post_voc_ip, n_pre_voc_er, n_post_voc_er) %>%
  pivot_longer(cols = c("n_pre_voc_ip", "n_post_voc_ip", "n_pre_voc_er", "n_post_voc_er"), 
               names_to = "variable", values_to = "count") %>%
  mutate(treat = as.numeric(cohort_name == 'oxbryta'), 
         post = as.numeric(variable %in% c('n_post_voc_ip', 'n_post_voc_er')),
         outcome = stringr::str_extract(variable, '[a-z]*$'))
hist2 <- ggplot(post_matching_2_long) + 
  geom_histogram(aes(x = count, fill = cohort_name), position = "dodge", binwidth = 1) + facet_grid(outcome~post) + 
  coord_cartesian(xlim=c(0, 20))
print(hist2)
ggsave(hist2, filename = file.path(plot_dir, 'histogram_model_2.png'), width = 6, height = 5)
drive_plot3 <- drive_upload(file.path(plot_dir, 'histogram_model_2.png'), path = plot_drive, overwrite = T)

summ <- post_matching_2_long %>% group_by(outcome, treat, post) %>%
  summarize(n = n(), mean = mean(count), voc1p = sum(count >= 1), voc2p = sum(count >= 2), voc3p = sum(count >= 3))
print(summ)
sheet_write(summ, ss = output_ss, sheet = 'outcome_summary2')

```

```{r matching_design_2_modeling}
ip_model <- glm(count ~ treat*post, family = poisson(link = 'identity'), data = post_matching_2_long %>% filter(outcome == 'ip'))
er_model <- glm(count ~ treat*post, family = poisson(link = 'identity'), data = post_matching_2_long %>% filter(outcome == 'er'))
ip_model_1p <- lm(I(count>=1) ~ treat*post, data = post_matching_2_long %>% filter(outcome == 'ip'))
er_model_1p <- lm(I(count>=1) ~ treat*post, data = post_matching_2_long %>% filter(outcome == 'er'))
ip_model_2p <- lm(I(count>=2) ~ treat*post, data = post_matching_2_long %>% filter(outcome == 'ip'))
er_model_2p <- lm(I(count>=2) ~ treat*post, data = post_matching_2_long %>% filter(outcome == 'er'))
ip_model_3p <- lm(I(count>=3) ~ treat*post, data = post_matching_2_long %>% filter(outcome == 'ip'))
er_model_3p <- lm(I(count>=3) ~ treat*post, data = post_matching_2_long %>% filter(outcome == 'er'))

```

```{r matching_design_2_boot_ci}
fit_did <- function(data_wide, ind) {
  data_long <- 
    data_wide[ind,] %>% 
    select(cohort_name, n_pre_voc_ip, n_post_voc_ip, n_pre_voc_er, n_post_voc_er) %>%
    pivot_longer(cols = c("n_pre_voc_ip", "n_post_voc_ip", "n_pre_voc_er", "n_post_voc_er"), 
                 names_to = "variable", values_to = "count") %>%
    mutate(treat = as.numeric(cohort_name == 'oxbryta'), 
           post = as.numeric(variable %in% c('n_post_voc_ip', 'n_post_voc_er')),
           outcome = stringr::str_extract(variable, '[a-z]*$'))
  
  ip_model <- glm(count ~ treat*post, family = poisson(link = 'identity'), data = data_long %>% filter(outcome == 'ip'))
  er_model <- glm(count ~ treat*post, family = poisson(link = 'identity'), data = data_long %>% filter(outcome == 'er'))
  ip_model_1p <- lm(I(count>=1) ~ treat*post, data = data_long %>% filter(outcome == 'ip'))
  er_model_1p <- lm(I(count>=1) ~ treat*post, data = data_long %>% filter(outcome == 'er'))
  ip_model_2p <- lm(I(count>=2) ~ treat*post, data = data_long %>% filter(outcome == 'ip'))
  er_model_2p <- lm(I(count>=2) ~ treat*post, data = data_long %>% filter(outcome == 'er'))
  ip_model_3p <- lm(I(count>=3) ~ treat*post, data = data_long %>% filter(outcome == 'ip'))
  er_model_3p <- lm(I(count>=3) ~ treat*post, data = data_long %>% filter(outcome == 'er'))

  c(coef(ip_model)['treat:post'], coef(er_model)['treat:post'],
    coef(ip_model_1p)['treat:post'], coef(er_model_1p)['treat:post'],
    coef(ip_model_2p)['treat:post'], coef(er_model_2p)['treat:post'],
    coef(ip_model_3p)['treat:post'], coef(er_model_3p)['treat:post'])
}
fit_did(post_matching_2)
cl <- makeCluster(detectCores())
res <- boot(post_matching_2, fit_did, R = 1000, parallel = "snow", cl = cl)
stopCluster(cl)
ci <- t(sapply(1:8, function(i) boot.ci(res, type = c('basic'), index = i)$basic[c(4,5)]))

model_df <- data.frame(
  model = rep(c('counts', 'voc>=1', 'voc>=2', 'voc>=3'), each = 2),
  outcome = rep(c('ip', 'er'), 4), 
  rbind(coef(ip_model), coef(er_model), coef(ip_model_1p), coef(er_model_1p), 
        coef(ip_model_2p), coef(er_model_2p), coef(ip_model_3p), coef(er_model_3p)),
  lower = ci[,1],
  upper = ci[,2]
  )

sheet_write(model_df, ss = output_ss, sheet = 'did_model2')
```